#!/bin/bash

# RVM post installation setup
# (Ruby Version Manager)
# <http://rvm.io/>

# steps required after installation with yay
# – additionally, zsh or bash must be started
#   with --login option to get ruby working
mkdir -p ~/.rvm/archives ~/.rvm/rubies ~/.rvm/src

# to setup Ruby 3.1.4 as default:
# zsh --login
# rvm install 3.1.4
# rvm --default use 3.1.4
# ruby --version
