#!/usr/bin/env ruby
# frozen_string_literal: true

require 'socket'
require 'webrick'

def read_local_ip
  Socket.ip_address_list.detect do |addr|
    addr.ipv4? && !addr.ipv4_loopback?
  end&.ip_address || '127.0.0.1'
end

port = 8000
local_ip = read_local_ip
document_root = File.expand_path('..', __dir__)

server = WEBrick::HTTPServer.new(
  Port: port,
  DocumentRoot: document_root
)

puts "\nServing Termux setup script at:"
puts "http://#{local_ip}:#{port}/termux/setup"
puts "\nOn your Android device, run:"
puts "curl http://#{local_ip}:#{port}/termux/setup | bash"
puts "\nPress Ctrl+C to stop the server\n"

trap('INT') { server.shutdown }
server.start
