" init project environment variables
let g:proj_path=expand("`pwd`")
let g:proj_file=expand(g:proj_path.".vimproject")

" tags
let g:gutentags_ctags_exclude = ['*.css', '*.html', '*.js']

" PHP-CS-FIXER
let g:php_cs_fixer_level = 'all' " with 'symfony' default, level would overwrite config filter removals!
let g:php_cs_fixer_config_file = g:proj_path . '.php_cs'

" load default session, but only when not in diff mode
if !&diff
    source .vimsession
endif

" preserve buffers ... and history of commands, searches, ...
exec "set viminfo=%,'50,<1000,s100,:50,@10,/50,n" . g:proj_path . ".viminfo"

" Save session and viminfo, quit
exec "nmap <silent> <F10> :mksession! " . g:proj_path . ".vimsession<CR>:wviminfo! " . g:proj_path . ".viminfo<CR>:qa!<CR>"

" prevent vim from writing newline to last line of file
" set binary
" set noeol

" set file formats
set ff=unix

" tab options for all files
set expandtab " do use spaces instead of tabs
set shiftwidth=4
set softtabstop=4
set tabstop=4

" tig integration
noremap T :!tig status<CR>

" fzf
exec "nmap <silent> <leader>g :FzFiles " . g:proj_path . "<CR>"

" Spell check
"setlocal spell spelllang=en_us
"setlocal spell spelllang=de_de
"set complete+=kspell

" {{{ COLORSCHEME
" colo kellys
colo moria
" colo bclear
" }}}



