# instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# general
bindkey -v
setopt autocd extendedglob
unsetopt beep

# completion
# see </usr/share/doc/zsh-completions/README.md>
# activate completion system and compdef command
# (must be available before most other stuff)
# (compdef error occurred with rvm ruby enabled
#  when this section was further below)
autoload -Uz compinit
compinit

# environment (to be read before aliases)
source ~/.zsh/environment

# aliases
source ~/.zsh/aliases

# direnv
eval "$(direnv hook zsh)"

# functions
source ~/.zsh/functions

# projects
find ~ -maxdepth 1 -type d -iname '*.dotfiles*' | while read dotfiles
do
  rcfile="${dotfiles}/zsh/zshrc"
  if [ -f "${rcfile}" ]; then
      source "${rcfile}"
  fi
done

# plugins
export ZSH_PLUGINS=/usr/share/zsh/plugins # Arch packages
eval "$(sheldon source)" # sheldon

# rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# history
# see </usr/share/doc/zsh-history-substring-search/README.md>
source $ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey '^[[A' history-substring-search-up # cursor up, via cat -v
bindkey '^[[B' history-substring-search-down # cursor down
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# autosuggestions
# see </usr/share/doc/zsh-autosuggestions/README.md>
source $ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)
bindkey '^ ' autosuggest-accept # ctrl + space
bindkey '^L' autosuggest-accept # ctrl + l
bindkey '^J' autosuggest-execute # ctrl + j
bindkey '^H' autosuggest-clear # ctrl + h
bindkey '^K' autosuggest-fetch # ctrl + k

# rupa/z jump-around
source /usr/share/z/z.sh

# prompt
# see </usr/share/zsh-theme-powerlevel10k/README.md>
# run `p10k configure` or edit ~/.p10k.zsh for customization
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# allow output on zsh init, and output quote
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
fortune 1% wisdom 99% $HOME/dotfiles/goodies/fortune
