# <https://github.com/robbyrussell/oh-my-zsh>


# ZSH PATHES
export ZSH=/usr/local/src/oh-my-zsh
export ZSH_CUSTOM=~/.zsh
export HISTFILE=$ZSH_CUSTOM/history/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000
export ZSH_PRIVATE=~/datafiles/zsh


# SETTINGS

# theme
export ZSH_THEME="fishy"

# disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"


# PLUGINS
plugins=(
        # <$ZSH/plugins/globalias/README.md>
        globalias

        # <$ZSH/plugins/history-substring-search/README.md>
        history-substring-search

        # <$ZSH/plugins/docker/README.md>
        docker

        # <$ZSH/plugins/docker-compose/README.md>
        docker-compose

        # <$ZSH/plugins/rails/rails.plugin.zsh>
        rails

        # <$ZSH/plugins/vi-mode/README.md>
        #vi-mode

        # <$ZSH_CUSTOM/plugins/zsh-autosuggestions/README.md>
        zsh-autosuggestions

        # <$ZSH_CUSTOM/plugins/zsh-syntax-highlighting/README.md>
        zsh-syntax-highlighting
)

export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)


# COMPLETION

## `pass` completion
fpath=(/usr/share/zsh/vendor-completions/_pass $fpath)

## overwrite hosts completion to avoid `/etc/hosts` to be included,
## which contains too many hosts (from <http://someonewhocares.org/hosts/hosts>)
## (functionality introduced via ZSH/lib/completion.zsh)
##
## use -/etc/hosts- and known_hosts for hostname completion
#[ -r /etc/ssh/ssh_known_hosts ] && _global_ssh_hosts=(${${${${(f)"$(</etc/ssh/ssh_known_hosts)"}:#[\|]*}%%\ *}%%,*}) || _ssh_hosts=()
#[ -r ~/.ssh/known_hosts ] && _ssh_hosts=(${${${${(f)"$(<$HOME/.ssh/known_hosts)"}:#[\|]*}%%\ *}%%,*}) || _ssh_hosts=()
#hosts=(
#  "$_global_ssh_hosts[@]"
#  "$_ssh_hosts[@]"
#  "$HOST"
#  localhost
#)

zstyle ':completion:*:hosts' hosts $hosts

# completion zstyles according to http://www.linux-mag.com/id/1106/
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''

# completion ignore
zstyle ':completion:*:*' ignored-patterns '*ORIG_HEAD' # for git


# MORE

source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/environment
source $ZSH_CUSTOM/aliases
source $ZSH_CUSTOM/functions
source $ZSH_CUSTOM/misc
source $ZSH_CUSTOM/options

# use distinct host indication
# derived from $ZSH/themes/fishy.zsh-theme
local user_color='white'; [ $UID -eq 0 ] && user_color='magenta'
PROMPT='%{$bg[$user_color]%}%{$fg[black]%}%n@%m%{$reset_color%} %{$fg[$reset_color]%}$(_fishy_collapsed_wd)%{$reset_color%}%(!.#.>) '

# vi mode and keybindings
# -----------------------
# hint: to find out a terminal's key code for <enter> & co., follow this guide:
# <https://github.com/zsh-users/zsh-autosuggestions/issues/255#issuecomment-321879150>
bindkey -v
bindkey '^ ' autosuggest-accept # ctrl + space
bindkey '^L' autosuggest-accept # ctrl + l
bindkey '^J' autosuggest-execute # ctrl + j
bindkey '^H' autosuggest-clear # ctrl + h
bindkey '^K' autosuggest-fetch # ctrl + k

# Sven Guckes "Zsh" p. 109
autoload -U compinit && compinit
zmodload -i zsh/complist

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# set $OPERATION_SYSTEM for $DOTFILES/setup/* scripts
source $DOTFILES/bin/setosenv

# at end to fix completions
source $ZSH_PRIVATE/_zshrc

# and unset unwanted aliases from oh-my-zsh
unalias grep
alias grep='grep --color=auto'

# vim: ft=sh
