# ZSH PATHES

# <https://github.com/robbyrussell/oh-my-zsh>
export ZSH=/usr/local/src/oh-my-zsh

export ZSH_CUSTOM=~/.zsh

export HISTFILE=$ZSH_CUSTOM/history/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000

export ZSH_PRIVATE=~/datafiles/zsh


# SETTINGS

# Set to the name theme to load.
export ZSH_THEME="fishy"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"


# PLUGINS
# (see $ZSH/plugins/)

plugins=(
        composer
        command-not-found
        debian
        git
        history-substring-search
        screen
        sudo
        zsh-syntax-highlighting
)
# zsh-syntax-highlighting: must be initialized as git submodule in $ZSH


# COMPLETION

## Load completion for hub
#fpath=(/usr/local/src/hub/etc $fpath)
#autoload -U /usr/local/src/hub/etc/hub.zsh_completion(:t)

# overwrite hosts completion to avoid `/etc/hosts` to be included,
# which contains too many hosts (from <http://someonewhocares.org/hosts/hosts>)
# (functionality introduced via ZSH/lib/completion.zsh)
#
# use -/etc/hosts- and known_hosts for hostname completion
[ -r /etc/ssh/ssh_known_hosts ] && _global_ssh_hosts=(${${${${(f)"$(</etc/ssh/ssh_known_hosts)"}:#[\|]*}%%\ *}%%,*}) || _ssh_hosts=()
[ -r ~/.ssh/known_hosts ] && _ssh_hosts=(${${${${(f)"$(<$HOME/.ssh/known_hosts)"}:#[\|]*}%%\ *}%%,*}) || _ssh_hosts=()
hosts=(
  "$_global_ssh_hosts[@]"
  "$_ssh_hosts[@]"
  "$HOST"
  localhost
)

zstyle ':completion:*:hosts' hosts $hosts

# completion zstyles according to http://www.linux-mag.com/id/1106/
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''


# ENVIRONMENT VARIABLES
## TODO mv to appropriate place (shell indep.)
# -- for very global settings, edit `/etc/login.defs`
# -- for global settings edit `/etc/environment`
# -- see `/etc/profile`, too
# -- yet, $PATH gets overwritten somewhere else

export EDITOR="vim"
export LESS="-R --ignore-case -P ?f%f:stdin.  line %lt–%lb/%L  ?e(END):%PB\%."
export JAVA_HOME="/usr/lib/jvm/default-java"
export GRAILS_HOME="/usr/local/lib/grails"
export GRAILS_OPTS="-server -Xmx1024M -Xms1024M -XX:PermSize=256m -XX:MaxPermSize=256m -Dfile.encoding=UTF-8"
alias grails=/usr/local/lib/grails/bin/grails
export PATH="$PATH:/home/t/bin:/home/t/bin-public"

# regular part read out via `manpath`, but MySQL is included anyways already
# export MANPATH="/usr/local/man:/usr/local/share/man:/usr/share/man:/home/t/lib/mysql/refman-5.6-en.man-gpl"

# vim : set ft=config :

# MORE
source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/aliases
source $ZSH_CUSTOM/functions
source $ZSH_CUSTOM/misc
source $ZSH_CUSTOM/options
source $ZSH_PRIVATE/_zshrc

# use distinct host indication
# derived from $ZSH/themes/fishy.zsh-theme
local user_color='blue'; [ $UID -eq 0 ] && user_color='magenta'
PROMPT='%{$bg[$user_color]%}%{$fg[black]%}%n@%m%{$reset_color%} %{$fg[$user_color]%}$(_fishy_collapsed_wd)%{$reset_color%}%(!.#.>) '

# vi mode
# bindkey -v

# enable zsh completion => required for running <https://github.com/stecman/symfony-console-completion> (?)
# Sven Guckes "Zsh" p. 109
autoload -U compinit && compinit
zmodload -i zsh/complist

# load inspector completion
inspector zsh --bind=inspector --program=inspector | source /dev/stdin